#!/usr/bin/env bash
# ubuntu-opencode.sh — install and manage an OpenCode server on Ubuntu/Linux.
#
# Runs OpenCode as a per-user systemd service so it survives terminal exits
# and reboots without root. Safe to re-run: every subcommand is idempotent.
#
#   bash ubuntu-opencode.sh install    # install/refresh OpenCode + the service
#   bash ubuntu-opencode.sh start      # start the service
#   bash ubuntu-opencode.sh stop       # stop the service
#   bash ubuntu-opencode.sh restart    # restart the service
#   bash ubuntu-opencode.sh status     # service state and listening check
#   bash ubuntu-opencode.sh logs       # follow the server log
#   bash ubuntu-opencode.sh update     # upgrade OpenCode, then restart
#   bash ubuntu-opencode.sh password   # print the server password for the app
#
# Configuration (environment variables, all optional):
#   OPENCODE_PORT      port to listen on            (default 4096)
#   OPENCODE_HOSTNAME  address to bind              (default 127.0.0.1)
#
# The server binds loopback only. An OpenCode server runs shell commands with
# your account's permissions, so exposing it to a network — even a home or
# office LAN — hands anyone on that network your shell. To reach it from a
# phone, forward the port over something authenticated and encrypted:
# 'adb reverse tcp:4096 tcp:4096' over USB, an SSH tunnel, or a Tailscale or
# WireGuard address. A password is generated on install and required on every
# request; it lives in a 0600 environment file, never on the command line.
#
# Full walkthrough: docs/ubuntu-host.md in https://github.com/Eslamasabry/opencode-mobile-next
set -euo pipefail

readonly SERVICE_NAME="opencode-serve"
readonly PORT="${OPENCODE_PORT:-4096}"
readonly BIND_HOST="${OPENCODE_HOSTNAME:-127.0.0.1}"
readonly ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/$SERVICE_NAME.env"
readonly UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
readonly UNIT_FILE="$UNIT_DIR/$SERVICE_NAME.service"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

usage() {
  sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
}

require_systemd_user() {
  command -v systemctl >/dev/null 2>&1 ||
    fail "systemd is required. On WSL or containers, run 'opencode serve' directly instead."
  systemctl --user show-environment >/dev/null 2>&1 ||
    fail "The systemd user manager is not reachable. Log in as this user (not via 'su') and retry."
}

find_opencode() {
  local candidate
  for candidate in \
    "$(command -v opencode 2>/dev/null || true)" \
    "$HOME/.opencode/bin/opencode" \
    "$HOME/.local/bin/opencode" \
    "$HOME/.bun/bin/opencode"; do
    if [[ -n "$candidate" && -x "$candidate" ]]; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

install_opencode_if_missing() {
  if find_opencode >/dev/null; then
    echo "==> OpenCode is already installed: $(find_opencode)"
    return
  fi
  echo "==> Installing OpenCode with the official installer"
  curl -fsSL https://opencode.ai/install | bash
  find_opencode >/dev/null ||
    fail "The installer finished but 'opencode' was not found. Open a new shell and re-run this script."
}

validate_bind() {
  [[ "$PORT" =~ ^[0-9]+$ ]] && ((PORT >= 1 && PORT <= 65535)) ||
    fail "OPENCODE_PORT must be a number between 1 and 65535 (got '$PORT')."
  [[ "$BIND_HOST" =~ ^[A-Za-z0-9.:_-]+$ ]] ||
    fail "OPENCODE_HOSTNAME contains characters that are not a valid address."
  case "$BIND_HOST" in
    127.0.0.1|localhost|::1) ;;
    *)
      cat >&2 <<WARN
WARNING: binding $BIND_HOST exposes this server beyond loopback.
An OpenCode server runs shell commands as $USER, so anyone who can reach
this address and learns the password can run code on this machine. Plain
HTTP also sends that password in clear text. Prefer loopback plus an SSH
tunnel, adb reverse, or Tailscale/WireGuard.
WARN
      [[ "${OPENCODE_ALLOW_REMOTE_BIND:-}" == "1" ]] ||
        fail "Refusing to bind $BIND_HOST. Re-run with OPENCODE_ALLOW_REMOTE_BIND=1 if you accept the risk."
      ;;
  esac
}

ensure_password() {
  if [[ -s "$ENV_FILE" ]] && grep -q '^OPENCODE_SERVER_PASSWORD=.\+$' "$ENV_FILE"; then
    return
  fi
  local generated
  generated="$(head -c 32 /dev/urandom | base64 | tr -d '=+/[:space:]' | cut -c1-32)"
  [[ -n "$generated" ]] || fail "Could not generate a server password."
  mkdir -p "$(dirname "$ENV_FILE")"
  local previous
  previous="$(umask)"
  umask 077
  printf 'OPENCODE_SERVER_PASSWORD=%s\n' "$generated" >"$ENV_FILE"
  umask "$previous"
  chmod 600 "$ENV_FILE"
  echo "==> Generated a server password in $ENV_FILE (0600)"
}

write_unit() {
  local opencode_bin
  opencode_bin="$(find_opencode)" || fail "OpenCode is not installed. Run: bash $0 install"
  validate_bind
  ensure_password
  mkdir -p "$UNIT_DIR"
  cat >"$UNIT_FILE" <<UNIT
# Generated by ubuntu-opencode.sh — safe to re-run 'install' to refresh.
[Unit]
Description=OpenCode server for phone and remote clients
After=network-online.target

[Service]
# The password is read from a 0600 file so it never appears in the unit
# text, in 'ps' output, or in the journal.
EnvironmentFile=$ENV_FILE
ExecStart=$opencode_bin serve --hostname $BIND_HOST --port $PORT
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
UNIT
  systemctl --user daemon-reload
  echo "==> Wrote $UNIT_FILE (bind $BIND_HOST, port $PORT)"
}

post_install_hints() {
  cat <<HINTS

Next steps:
  - Keep the server running after you log out:
      loginctl enable-linger "$USER"
  - The server listens on $BIND_HOST:$PORT only. Reach it from a phone over
    an authenticated, encrypted path rather than opening a firewall port:
      USB:       adb reverse tcp:$PORT tcp:$PORT   then connect to http://127.0.0.1:$PORT
      SSH:       ssh -N -L $PORT:127.0.0.1:$PORT $USER@<this-machine>
      Tailscale: connect to http://<tailscale-name>:$PORT (its network is authenticated)
  - Read the server password when the app asks for it:
      bash $0 password
HINTS
}

listening_check() {
  if command -v ss >/dev/null 2>&1 && ss -ltn 2>/dev/null | grep -q ":$PORT "; then
    echo "==> Listening on port $PORT"
  else
    echo "==> Nothing is listening on port $PORT yet"
  fi
}

cmd_install() {
  require_systemd_user
  install_opencode_if_missing
  write_unit
  systemctl --user enable --now "$SERVICE_NAME"
  systemctl --user --no-pager --full status "$SERVICE_NAME" || true
  listening_check
  post_install_hints
}

cmd_update() {
  require_systemd_user
  local opencode_bin
  opencode_bin="$(find_opencode)" || fail "OpenCode is not installed. Run: bash $0 install"
  echo "==> Upgrading OpenCode"
  "$opencode_bin" upgrade
  # The binary path can change across upgrades; refresh the unit before restart.
  write_unit
  systemctl --user restart "$SERVICE_NAME"
  echo "==> Restarted $SERVICE_NAME"
  listening_check
}

main() {
  local command="${1:-}"
  case "$command" in
    install) cmd_install ;;
    start)
      require_systemd_user
      systemctl --user start "$SERVICE_NAME"
      listening_check
      ;;
    stop)
      require_systemd_user
      systemctl --user stop "$SERVICE_NAME"
      ;;
    restart)
      require_systemd_user
      systemctl --user restart "$SERVICE_NAME"
      listening_check
      ;;
    status)
      require_systemd_user
      systemctl --user --no-pager --full status "$SERVICE_NAME" || true
      listening_check
      ;;
    logs)
      require_systemd_user
      journalctl --user -u "$SERVICE_NAME" -f
      ;;
    update) cmd_update ;;
    password)
      [[ -s "$ENV_FILE" ]] || fail "No password yet. Run: bash $0 install"
      sed -n 's/^OPENCODE_SERVER_PASSWORD=//p' "$ENV_FILE"
      ;;
    *)
      usage
      exit 64
      ;;
  esac
}

main "$@"
